version: '3'

services:
  apache_web:
    container_name: apache_web
    build:
      context: ./apache/
      dockerfile: ./Dockerfile
    command: apache2ctl -DFOREGROUND
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ./web_data:/home/web_data
   
  mysql_web:
    container_name: mysql_web
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./mysql/
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: cBc9029U
      MYSQL_ONE_TIME_PASSWORD: cBc9029U
      MYSQL_USER: videos4u
      MYSQL_PASSWORD: olah6aeQuie7Oishol4Eej6oofee3aeg
      MYSQL_DATABASE: videos4u_web
    ports:
    - "33060:3306"
     